# Generated by Django 3.1.1 on 2022-07-19 10:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('billing_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_cost', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='order.category')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('menu_id', models.OneToOneField(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='order.menu')),
                ('remaining_quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(default=4)),
                ('status', models.CharField(choices=[('occupied', 'occupied'), ('unoccupied', 'unoccupied')], default='unoccupied', max_length=30)),
                ('customer_id', models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.customers')),
                ('order_id', models.ForeignKey(db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_mode', models.CharField(choices=[('cash', 'cash'), ('upi', 'upi'), ('debit_card', 'debit_card'), ('credit_card', 'credit_card'), ('cheque', 'cheque')], default='cash', max_length=30)),
                ('status', models.CharField(choices=[('success', 'success'), ('pending', 'pending'), ('failed', 'failed')], default='success', max_length=30)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('billing_id', models.ForeignKey(db_column='billing_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.billing')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('order_items_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('menu_id', models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, to='order.menu')),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='order.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('ratings', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.CharField(max_length=100, null=True)),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='order.orders')),
            ],
        ),
        migrations.AddField(
            model_name='billing',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.customers'),
        ),
        migrations.AddField(
            model_name='billing',
            name='order_id',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='order.orders'),
        ),
    ]
